version: '3.7'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  public:
    external: true
