version: '3.7'
services:
  postgres:
    image: postgres:11
    container_name: sqlfns-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=playground
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./database/postgres.sh:/docker-entrypoint-initdb.d/dbinit.sh
